# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20171113_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность вопроса')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Полный текст вопроса')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
