# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Количество дислайков'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
