# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 21:44
from __future__ import unicode_literals

import ask.managers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_auto_20171113_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ask.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ask.Question', verbose_name='Вопрос, на который выполняется ответ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default='404', max_length=50, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания профиля'),
        ),
    ]
