# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20171211_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(default='avatars/emptyUser.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
