# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_auto_20171216_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Answer author'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Answer date'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ask.Question', verbose_name='Answered question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Answer full text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Question author'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Question date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Question aviability'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='ask.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question full text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default='404', max_length=15, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='User rating'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Profile creation date'),
        ),
        migrations.DeleteModel(
            name='AnswerLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='QuestionLike',
        ),
    ]
